/**
 * REFACTORED HeroAnimated Component
 * 
 * This is an example of how HeroAnimated should be refactored to use
 * the new animation architecture. This ensures visual parity between
 * builder preview and exported output.
 * 
 * Key Changes:
 * 1. Uses serializable animation config from props
 * 2. Uses shared animation hooks and renderer
 * 3. No builder-only dependencies
 * 4. Works identically in builder and export
 */

"use client";
import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import TextEditable from "../../TextEditable";
import { 
  BackgroundAnimationConfig, 
  getDefaultAnimationConfig, 
  mergeAnimationConfig 
} from "@/lib/animations/config";
import { 
  useParticleCanvas, 
  AnimatedGrid, 
  FloatingOrbs,
  useMousePosition 
} from "@/lib/animations/hooks";
import { generateGradientStyle } from "@/lib/animations/renderer";

export default function HeroAnimatedRefactored({
  title = "Build Amazing Websites",
  subtitle = "Create stunning, responsive websites in minutes with our powerful drag-and-drop builder.",
  buttonText = "Get Started",
  buttonText2 = "Learn More",
  onEdit,
  backgroundColor = "#0f172a",
  gradientColors,
  titleColor = "#ffffff",
  subtitleColor = "#e2e8f0",
  buttonBackground = "#4f46e5",
  buttonTextColor = "#ffffff",
  button2Background = "transparent",
  button2TextColor = "#ffffff",
  // NEW: Animation config from props (or use default)
  animationConfig: userAnimationConfig,
}: {
  title?: string;
  subtitle?: string;
  buttonText?: string;
  buttonText2?: string;
  onEdit?: (field: string) => void;
  backgroundColor?: string;
  gradientColors?: string[];
  titleColor?: string;
  subtitleColor?: string;
  buttonBackground?: string;
  buttonTextColor?: string;
  button2Background?: string;
  button2TextColor?: string;
  animationConfig?: Partial<BackgroundAnimationConfig>;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  // Get animation config (merge user config with defaults)
  const defaultConfig = getDefaultAnimationConfig("heroAnimated");
  
  // If gradientColors provided, merge into config
  if (gradientColors && gradientColors.length >= 2) {
    defaultConfig.gradient = {
      ...defaultConfig.gradient,
      colors: gradientColors,
    };
  }
  
  const animationConfig = mergeAnimationConfig(
    userAnimationConfig || {},
    defaultConfig
  );

  // Use shared animation hooks
  useParticleCanvas(animationConfig, canvasRef);
  const mousePos = useMousePosition(true); // Enable mouse tracking for parallax

  // Generate background style from config
  const backgroundStyle = generateGradientStyle(animationConfig);
  if (!backgroundStyle.background && !backgroundStyle.backgroundColor) {
    // Fallback to backgroundColor if no gradient
    backgroundStyle.backgroundColor = backgroundColor;
  }

  return (
    <>
      {/* CSS keyframes are generated by export pipeline */}
      <section
        ref={ref}
        className="relative min-h-screen flex items-center justify-center overflow-hidden"
        style={backgroundStyle}
      >
        {/* Animated Canvas Particles - uses shared hook */}
        {animationConfig.overlay?.particles?.enabled && (
          <canvas
            ref={canvasRef}
            className="absolute inset-0 opacity-30"
            style={{ zIndex: 1 }}
            data-particle
          />
        )}

        {/* Animated Grid Background - uses shared component */}
        <AnimatedGrid config={animationConfig} />

        {/* Floating Orbs - uses shared component */}
        <FloatingOrbs config={animationConfig} />

        {/* Content */}
        <div
          className="relative z-10 max-w-7xl mx-auto px-6 text-center"
          style={{
            transform: `translate(${mousePos.x * 0.1}px, ${mousePos.y * 0.1}px)`,
          }}
        >
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, ease: "easeOut" }}
          >
            {/* Badge */}
            <motion.div
              className="inline-block mb-8"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={isInView ? { opacity: 1, scale: 1 } : {}}
              transition={{ delay: 0.2, duration: 0.5 }}
            >
              <span
                className="px-6 py-2 rounded-full text-sm font-semibold backdrop-blur-md border"
                style={{
                  backgroundColor: "rgba(255, 255, 255, 0.1)",
                  borderColor: "rgba(255, 255, 255, 0.2)",
                  color: titleColor,
                }}
              >
                ✨ New: AI-Powered Builder
              </span>
            </motion.div>

            {/* Title */}
            <motion.h1
              className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-extrabold mb-6 leading-tight"
              style={{ color: titleColor }}
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: 0.3, duration: 0.8 }}
            >
              <TextEditable onClick={() => onEdit?.("title")}>
                {title}
              </TextEditable>
            </motion.h1>

            {/* Subtitle */}
            <motion.p
              className="text-xl md:text-2xl mb-12 max-w-3xl mx-auto leading-relaxed"
              style={{ color: subtitleColor }}
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: 0.5, duration: 0.8 }}
            >
              <TextEditable onClick={() => onEdit?.("subtitle")}>
                {subtitle}
              </TextEditable>
            </motion.p>

            {/* Buttons */}
            <motion.div
              className="flex flex-col sm:flex-row gap-6 justify-center items-center"
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: 0.7, duration: 0.8 }}
            >
              <motion.button
                whileHover={{ scale: 1.05, y: -2 }}
                whileTap={{ scale: 0.95 }}
                className="px-10 py-5 rounded-2xl text-lg font-bold shadow-2xl transition-all duration-300 relative overflow-hidden group"
                style={{
                  background: buttonBackground,
                  color: buttonTextColor,
                }}
              >
                <span className="relative z-10">
                  <TextEditable onClick={() => onEdit?.("buttonText")}>
                    {buttonText}
                  </TextEditable>
                </span>
                <motion.div
                  className="absolute inset-0 bg-white/20"
                  initial={{ x: "-100%" }}
                  whileHover={{ x: "100%" }}
                  transition={{ duration: 0.5 }}
                />
              </motion.button>

              {buttonText2 && (
                <motion.button
                  whileHover={{ scale: 1.05, y: -2 }}
                  whileTap={{ scale: 0.95 }}
                  className="px-10 py-5 rounded-2xl text-lg font-bold border-2 backdrop-blur-md transition-all duration-300"
                  style={{
                    background: button2Background,
                    color: button2TextColor,
                    borderColor: button2TextColor,
                  }}
                >
                  <TextEditable onClick={() => onEdit?.("buttonText2")}>
                    {buttonText2}
                  </TextEditable>
                </motion.button>
              )}
            </motion.div>
          </motion.div>
        </div>

        {/* Scroll Indicator */}
        <motion.div
          className="absolute bottom-10 left-1/2 transform -translate-x-1/2 z-10"
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          <div
            className="w-6 h-10 rounded-full border-2 flex justify-center p-2"
            style={{ borderColor: titleColor }}
          >
            <motion.div
              className="w-1 h-3 rounded-full"
              style={{ backgroundColor: titleColor }}
              animate={{ y: [0, 12, 0] }}
              transition={{ duration: 1.5, repeat: Infinity }}
            />
          </div>
        </motion.div>
      </section>
    </>
  );
}

